# Generated by Django 4.2.9 on 2026-01-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0002_comment_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="name",
            new_name="subject",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="published_date",
        ),
    ]
