# Generated by Django 4.2.9 on 2026-01-28 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("comment", "0003_rename_name_comment_subject_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="subject",
        ),
    ]
